Algoritmo "problema_media_ponderada"


//ESTRUTURA PARA

Var

 peso1, peso2, peso3, x1, x2, x3, media : real
 n, i : inteiro


Inicio

escreva("Quantos casos você vai digitar? ")
leia(n)



 para i de 1 ate n faca
  escreval("Digite três números:")
  leia(x1)
  leia(x2)
  leia(x3)

 media <- ((x1 * 2) + (x2 * 3) + (x3 * 5)) / 10

  escreval("MEDIA: ", media:2:1)
 fimpara



   
   
   
   
Fimalgoritmo


