Algoritmo "problema_idade"

Var

 nome, nome1 : caractere
 idade, idade1 : inteiro
 media : real

Inicio

 escreval("Digite os dados da primeira pessoa: ")
 escreva("Nome: ")
 leia(nome)
 escreva("Idade: ")
 leia(idade)
 escreval("Digite os dados da segunda pessoa: ")
 escreva("Nome: ")
 leia(nome1)
 escreva("Idade: ")
 leia(idade1)
 
 media <- (idade + idade1) / 2
 
 escreva("A idade média entre ", nome, " e " , nome1, " é igual a:", media, " anos")





Fimalgoritmo